[en]
title = "My Website"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[fa]
title = "وبسایت من"

contentDir = "content/persian" 
weight = 2
LanguageDirection = "rtl" 
LanguageName = "FA"
[fa.params]
description = """
کورس زنبوری

علاقه مند به فناوری اطلاعات
علاقه مند به تحقیق و پژوهش

-کلید PGP- 
0575887F49213EB4EE8D951D912DD243017C1570
"""