
title = "Kouros Zanbouri"
author = "Kouros Zanbouri"
#copyright = "2020-2021"
description = """
Call me Kouros
IT enthusiast, Researcher
-PGP Fingerprint- 
0575887F49213EB4EE8D951D912DD243017C1570
"""

profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = ["css/academicons.css", "css/academicons.min.css"]
# example ["js/custom.js"]
customJs = [] 
mainSections = [""]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[socialIcons]]
icon = "ai ai-publons-square ai-3x"
title = "Publons/Web of Science"
url = "https://www.webofscience.com/wos/author/record/1651032"


[[socialIcons]]
icon = "ai ai-google-scholar-square ai-3x"
title = "Google Scholar"
url = "https://scholar.google.com/citations?user=0Xr6wVQAAAAJ&hl=en"

[[socialIcons]]
icon = "fab fa-orcid"
title = "orcid"
url = "https://orcid.org/0000-0003-0252-8282"

[[socialIcons]]
icon = "ai ai-researchgate-square ai-3x"
title = "Researchgate"
url = "https://www.researchgate.net/profile/Kouros-Zanbouri-2"

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/kouros-zanbouri/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/KourosZanbouri/"

[[socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/kouroszanbouri/"


[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@example.com"

[[socialIcons]]
icon = "fab fa-telegram"
title = "e-mail"
url = "https://t.me/KourosZ"


[mermaid]
# enable = true
