baseURL = "https://kouroszanbouri.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true



# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[services]
# Enable Disqus.Disqus.Shortname
  [services.disqus]
    #shortname = 'your-disqus-shortname'
# Google Analytics
  [services.googleAnalytics]
    ID = 'G-WE97LMG20N'
    

[Languages]
[Languages.en]

weight = 1
LanguageName = "EN"
contentDir = "content/english"
description = """
IT enthusiast, Researcher
-PGP Fingerprint- 
0575887F49213EB4EE8D951D912DD243017C1570
"""


[Languages.fa]
contentDir = "content/persian" 
weight = 2
LanguageDirection = "rtl" 
LanguageName = "FA"
description = """

علاقه مند به فناوری اطلاعات
علاقه مند به تحقیق و پژوهش

-کلید PGP- 
0575887F49213EB4EE8D951D912DD243017C1570
"""



[params]
title = "Kouros Zanbouri"
author = "Kouros Zanbouri"
copyright = "2020-{{ YEAR }}"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
#customCss = ["css/academicons.css", "css/academicons.min.css"]
# example ["js/custom.js"]
#customJs = [] 
mainSections = [""]
#images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.



[[params.socialIcons]]
icon = "fab fa-google-scholar"
title = "Google Scholar"
url = "https://scholar.google.com/citations?user=0Xr6wVQAAAAJ&hl=en"

[[params.socialIcons]]
icon = "fab fa-orcid"
title = "orcid"
url = "https://orcid.org/0000-0003-0252-8282"

[[params.socialIcons]]
icon = "fab fa-researchgate"
title = "Researchgate"
url = "https://www.researchgate.net/profile/Kouros-Zanbouri-2"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/kouros-zanbouri/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/KourosZanbouri/"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/kouroszanbouri/"


[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@example.com"

[[params.socialIcons]]
icon = "fab fa-telegram"
title = "e-mail"
url = "https://t.me/KourosZ"

[[params.socialIcons]]
icon = "ai ai-publons-square ai-3x"
title = "Publons/Web of Science"
url = "https://www.webofscience.com/wos/author/record/1651032"

[mermaid]
# enable = true



[menu]

  [[Languages.en.menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[Languages.en.menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"
  
  
  
  [[Languages.fa.menu.main]]
  name = "خانه"
  identifier = "main"
  weight = 100
  url = "/fa/"

  [[Languages.fa.menu.main]]
  name = "نوشته ها"
  weight = 200
  identifier = "posts"
  url = "/fa/post/"

